"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var symbols = {
    coin: [
        "BTCUSDT",
        "DOGEUSDT",
        "SOLUSDT",
        "ADAUSDT",
        "WINUSDT",
        "FILUSDT",
        "COMPUSDT",
        "VETUSDT",
        "THETAUSDT",
        "ATOMUSDT",
        "CHZUSDT",
        "AAVEUSDT",
        "UNIUSDT",
        "ETHUSDT",
        "HOTUSDT",
        "DOTUSDT",
        "XRPUSDT",
        "BCHUSDT",
        "TRXUSDT",
        "LTCUSDT",
        "BNBUSDT",
        "XLMUSDT",
        "ETCUSDT",
        "LINKUSDT",
        "EGLDUSDT",
        "LRCUSDT",
        "MBOXUSDT",
        "VRAUSDT",
        "NEARUSDT",
        "COTIUSDT",
        "CELRUSDT",
        "ZILUSDT",
        "DENTUSDT",
        "AMPUSDT",
        "KAVAUSDT",
        "PORTOUSDT",
        "LAZIOUSDT",
        "RUNEUSDT",
        "FTTUSDT",
        "GRTUSDT",
        "XTZUSDT",
        "IOTAUSDT",
        "CRVUSDT",
        "OKBUSDT",
        "ROSEUSDT",
        "HTUSDT",
        "OMGUSDT",
        "ZECUSDT",
        "ONTUSDT",
        "C98USDT",
        "RACAUSDT",
        "PAXGUSDT",
        "APEUSDT",
        "GMTUSDT",
        "HEGICUSDT",
        "LOKAUSDT",
        "BUSDUSDT",
        "OOKIUSDT",
        "BSWUSDT",
        "LUNAUSDT",
        "USDCUSDT",
        "FLOWUSDT",
        "ACHUSDT",
        "LEVERUSDT",
        "QNTUSDT",
        "BLZUSDT",
        "FLUXUSDT",
        "TLMUSDT",
        "JSTUSDT",
        "TFUELUSDT",
        "GALUSDT",
        "API3USDT",
        "ANKRUSDT",
        "ENSUSDT",
        "SRMUSDT",
        "SUSHIUSDT",
        "WAVESUSDT",
        "MATICUSDT",
        "DUSKUSDT",
        "NEXOUSDT",
        "STGUSDT",
        "BADGERUSDT",
        "BNTUSDT",
        "EOSUSDT",
        "KEYUSDT",
        "JASMYUSDT",
        "WOOUSDT",
        "SXPUSDT",
        "LDOUSDT",
        "CHRUSDT",
        "VGXUSDT",
        "1INCHUSDT",
        "FETUSDT",
        "AGIXUSDT",
        "BITUSDT",
        "FXSUSDT",
        "IMXUSDT",
        "DCUSDT",
        "REEFUSDT",
        "STORJUSDT",
        "TUSDT",
        "BONEUSDT",
        "BLURUSDT",
        "GFTUSDT",
        "BICOUSDT",
        "RNDRUSDT",
        "ICPUSDT",
        "HIFIUSDT",
        "MASKUSDT",
        "ARBUSDT",
        "BURGERUSDT",
        "CAKEUSDT",
        "KSMUSDT",
        "BSVUSDT",
        "MKRUSDT",
        "MANAUSDT",
        "ONEUSDT",
        "FTMUSDT",
        "DAIUSDT",
        "AXSUSDT",
        "BLOKUSDT",
        "SLPUSDT",
        "ENJUSDT",
        "SANDUSDT",
        "GALAUSDT",
        "ALICEUSDT",
        "DYDXUSDT",
        "AUDIOUSDT",
        "BATUSDT",
        "CROUSDT",
        "AVAXUSDT",
        "PUNDIXUSDT",
        "SHIBUSDT",
        "XMRUSDT",
        "ALGOUSDT",
        "HBARUSDT",
        "YFIUSDT",
        "SNXUSDT",
        "APTUSDT",
        "FLRUSDT",
        "BALUSDT",
        "LPTUSDT",
        "GLMUSDT",
        "CVCUSDT",
        "NMRUSDT",
        "SNTUSDT",
        "ANTUSDT",
        "ZRXUSDT",
        "CVXUSDT",
        "ILVUSDT",
    ],
    ramzCoin: [
        [2, "BTCUSDT"],
        [10, "DOGEUSDT"],
        [96, "SOLUSDT"],
        [33, "ADAUSDT"],
        [48, "WINUSDT"],
        [51, "FILUSDT"],
        [136, "COMPUSDT"],
        [46, "VETUSDT"],
        [44, "THETAUSDT"],
        [42, "ATOMUSDT"],
        [40, "CHZUSDT"],
        [36, "AAVEUSDT"],
        [34, "UNIUSDT"],
        [3, "ETHUSDT"],
        [52, "HOTUSDT"],
        [29, "DOTUSDT"],
        [4, "XRPUSDT"],
        [23, "BCHUSDT"],
        [25, "TRXUSDT"],
        [5, "LTCUSDT"],
        [17, "BNBUSDT"],
        [19, "XLMUSDT"],
        [21, "ETCUSDT"],
        [26, "LINKUSDT"],
        [257, "EGLDUSDT"],
        [258, "LRCUSDT"],
        [259, "MBOXUSDT"],
        [264, "VRAUSDT"],
        [267, "NEARUSDT"],
        [268, "COTIUSDT"],
        [269, "CELRUSDT"],
        [270, "ZILUSDT"],
        [271, "DENTUSDT"],
        [275, "AMPUSDT"],
        [276, "KAVAUSDT"],
        [277, "PORTOUSDT"],
        [278, "LAZIOUSDT"],
        [280, "RUNEUSDT"],
        [281, "FTTUSDT"],
        [282, "GRTUSDT"],
        [283, "XTZUSDT"],
        [284, "IOTAUSDT"],
        [285, "CRVUSDT"],
        [287, "OKBUSDT"],
        [288, "ROSEUSDT"],
        [289, "HTUSDT"],
        [290, "OMGUSDT"],
        [291, "ZECUSDT"],
        [292, "ONTUSDT"],
        [293, "C98USDT"],
        [294, "RACAUSDT"],
        [296, "PAXGUSDT"],
        [298, "APEUSDT"],
        [299, "GMTUSDT"],
        [300, "HEGICUSDT"],
        [301, "LOKAUSDT"],
        [302, "BUSDUSDT"],
        [303, "OOKIUSDT"],
        [305, "BSWUSDT"],
        [307, "LUNAUSDT"],
        [310, "USDCUSDT"],
        [311, "FLOWUSDT"],
        [312, "ACHUSDT"],
        [313, "LEVERUSDT"],
        [314, "QNTUSDT"],
        [315, "BLZUSDT"],
        [316, "FLUXUSDT"],
        [317, "TLMUSDT"],
        [318, "JSTUSDT"],
        [319, "TFUELUSDT"],
        [320, "GALUSDT"],
        [321, "API3USDT"],
        [66, "ANKRUSDT"],
        [322, "ENSUSDT"],
        [323, "SRMUSDT"],
        [324, "SUSHIUSDT"],
        [326, "WAVESUSDT"],
        [71, "MATICUSDT"],
        [327, "DUSKUSDT"],
        [328, "NEXOUSDT"],
        [329, "STGUSDT"],
        [330, "BADGERUSDT"],
        [331, "BNTUSDT"],
        [76, "EOSUSDT"],
        [334, "KEYUSDT"],
        [335, "JASMYUSDT"],
        [336, "WOOUSDT"],
        [81, "SXPUSDT"],
        [337, "LDOUSDT"],
        [338, "CHRUSDT"],
        [340, "VGXUSDT"],
        [86, "1INCHUSDT"],
        [342, "FETUSDT"],
        [343, "AGIXUSDT"],
        [344, "BITUSDT"],
        [345, "FXSUSDT"],
        [346, "IMXUSDT"],
        [347, "DCUSDT"],
        [348, "REEFUSDT"],
        [349, "STORJUSDT"],
        [350, "TUSDT"],
        [351, "BONEUSDT"],
        [352, "BLURUSDT"],
        [353, "GFTUSDT"],
        [354, "BICOUSDT"],
        [355, "RNDRUSDT"],
        [101, "ICPUSDT"],
        [357, "HIFIUSDT"],
        [358, "MASKUSDT"],
        [360, "ARBUSDT"],
        [106, "BURGERUSDT"],
        [116, "CAKEUSDT"],
        [121, "KSMUSDT"],
        [131, "BSVUSDT"],
        [141, "MKRUSDT"],
        [146, "MANAUSDT"],
        [152, "ONEUSDT"],
        [237, "FTMUSDT"],
        [239, "DAIUSDT"],
        [243, "AXSUSDT"],
        [244, "BLOKUSDT"],
        [246, "SLPUSDT"],
        [247, "ENJUSDT"],
        [248, "SANDUSDT"],
        [249, "GALAUSDT"],
        [250, "ALICEUSDT"],
        [251, "DYDXUSDT"],
        [252, "AUDIOUSDT"],
        [253, "BATUSDT"],
        [254, "CROUSDT"],
        [255, "AVAXUSDT"],
        [50, "PUNDIXUSDT"],
    ],
    nobCoin: [
        ["BTCIRT", "BTCUSDT"],
        ["ETHIRT", "ETHUSDT"],
        ["LTCIRT", "LTCUSDT"],
        ["XRPIRT", "XRPUSDT"],
        ["BCHIRT", "BCHUSDT"],
        ["BNBIRT", "BNBUSDT"],
        ["EOSIRT", "EOSUSDT"],
        ["XLMIRT", "XLMUSDT"],
        ["ETCIRT", "ETCUSDT"],
        ["TRXIRT", "TRXUSDT"],
        ["DOGEIRT", "DOGEUSDT"],
        ["UNIIRT", "UNIUSDT"],
        ["DAIIRT", "DAIUSDT"],
        ["LINKIRT", "LINKUSDT"],
        ["DOTIRT", "DOTUSDT"],
        ["AAVEIRT", "AAVEUSDT"],
        ["ADAIRT", "ADAUSDT"],
        ["SHIBIRT", "SHIBUSDT"],
        ["FTMIRT", "FTMUSDT"],
        ["MATICIRT", "MATICUSDT"],
        ["AXSIRT", "AXSUSDT"],
        ["MANAIRT", "MANAUSDT"],
        ["SANDIRT", "SANDUSDT"],
        ["AVAXIRT", "AVAXUSDT"],
        ["MKRIRT", "MKRUSDT"],
        ["GMTIRT", "GMTUSDT"],
        ["USDCIRT", "USDCUSDT"],
        ["SOLIRT", "SOLUSDT"],
        ["ATOMIRT", "ATOMUSDT"],
        ["BATIRT", "BATUSDT"],
        ["GRTIRT", "GRTUSDT"],
        ["NEARIRT", "NEARUSDT"],
        ["APEIRT", "APEUSDT"],
        ["CHZIRT", "CHZUSDT"],
        ["QNTIRT", "QNTUSDT"],
        ["XMRIRT", "XMRUSDT"],
        ["GALAIRT", "GALAUSDT"],
        ["BUSDIRT", "BUSDUSDT"],
        ["ALGOIRT", "ALGOUSDT"],
        ["HBARIRT", "HBARUSDT"],
        ["YFIIRT", "YFIUSDT"],
        ["SNXIRT", "SNXUSDT"],
        ["ENJIRT", "ENJUSDT"],
        ["CRVIRT", "CRVUSDT"],
        ["FLOWIRT", "FLOWUSDT"],
        ["LDOIRT", "LDOUSDT"],
        ["FILIRT", "FILUSDT"],
        ["DYDXIRT", "DYDXUSDT"],
        ["APTIRT", "APTUSDT"],
        ["MASKIRT", "MASKUSDT"],
        ["FLRIRT", "FLRUSDT"],
        ["LRCIRT", "LRCUSDT"],
        ["COMPIRT", "COMPUSDT"],
        ["BALIRT", "BALUSDT"],
        ["ENSIRT", "ENSUSDT"],
        ["SUSHIIRT", "SUSHIUSDT"],
        ["LPTIRT", "LPTUSDT"],
        ["GLMIRT", "GLMUSDT"],
        ["API3IRT", "API3USDT"],
        ["ONEIRT", "ONEUSDT"],
        ["CVCIRT", "CVCUSDT"],
        ["NMRIRT", "NMRUSDT"],
        ["STORJIRT", "STORJUSDT"],
        ["SNTIRT", "SNTUSDT"],
        ["SLPIRT", "SLPUSDT"],
        ["ANTIRT", "ANTUSDT"],
        ["ZRXIRT", "ZRXUSDT"],
        ["IMXIRT", "IMXUSDT"],
        ["EGLDIRT", "EGLDUSDT"],
        ["BLURIRT", "BLURUSDT"],
        ["1INCHIRT", "1INCHUSDT"],
        ["CVXIRT", "CVXUSDT"],
        ["ILVIRT", "ILVUSDT"],
    ],
};
exports.default = symbols;
